org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8
# 多模块并行编译
org.gradle.parallel=true
android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
android.nonTransitiveRClass=true
# 启用 Configuration Cache
org.gradle.configuration-cache=true
# 构建缓存
org.gradle.caching=true
